export const DEFAULT = {
	LANGUAGE_TOGGLE: 'LANGUAGE_TOGGLE',
	ADD_TOAST: 'ADD_TOAST',
	REMOVE_TOAST: 'REMOVE_TOAST',
	NAVBAR_TOGGLE: 'NAVBAR_TOGGLE',
	ADD_CHAT_MESSAGE: 'ADD_CHAT_MESSAGE',
	ADD_CHAT_USER: 'ADD_CHAT_USER',
	REMOVE_CHAT_USER: 'REMOVE_CHAT_USER',
	FETCH_START: 'FETCH_START',
	FETCH_DONE: 'FETCH_DONE',
	FETCH_ERROR: 'FETCH_ERROR',
};
